import type { User, NFT } from './types';
import { PlaceHolderImages } from './placeholder-images';

const users: User[] = [
  { id: 'user1', displayName: 'Eco Warrior', photoURL: 'https://picsum.photos/seed/u1/100/100', email: 'warrior@demo.com', createdAt: new Date() },
  { id: 'user2', displayName: 'Green Thumb', photoURL: 'https://picsum.photos/seed/u2/100/100', email: 'green@demo.com', createdAt: new Date() },
  { id: 'user3', displayName: 'Ocean Guardian', photoURL: 'https://picsum.photos/seed/u3/100/100', email: 'ocean@demo.com', createdAt: new Date() },
];

const nfts: NFT[] = [
  {
    id: 'nft1',
    title: 'Amazonas Rebirth',
    description: 'This NFT funds the planting of 100 trees in the Brazilian Amazon, helping to restore vital ecosystems.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-1')?.imageUrl || '',
    impact: '100 trees planted',
    likes: 128,
    ownerId: 'user2',
    creatorId: 'user1',
    forSale: true,
    price: 1.5,
    category: 'Reforestation',
    isValid: true,
    isRecommended: true,
    createdAt: new Date('2023-10-01'),
  },
  {
    id: 'nft2',
    title: 'Pacific Gyre Cleanup',
    description: 'Contributes to removing 50kg of plastic from the Great Pacific Garbage Patch.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-2')?.imageUrl || '',
    impact: '50kg plastic removed',
    likes: 256,
    ownerId: 'user3',
    creatorId: 'user3',
    forSale: true,
    price: 2.2,
    category: 'Ocean Cleanup',
    isValid: true,
    isRecommended: true,
    createdAt: new Date('2023-11-15'),
  },
  {
    id: 'nft3',
    title: 'Savanna Elephant Adoption',
    description: 'Symbolically adopt and support the protection of an African savanna elephant for one year.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-3')?.imageUrl || '',
    impact: '1 elephant protected',
    likes: 95,
    ownerId: 'user1',
    creatorId: 'user2',
    forSale: false,
    price: 3.0,
    category: 'Wildlife Conservation',
    isValid: true,
    isRecommended: false,
    createdAt: new Date('2023-12-05'),
  },
  {
    id: 'nft4',
    title: 'Coral Reef Restoration',
    description: 'Funds the planting of a new coral colony in the Great Barrier Reef.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-4')?.imageUrl || '',
    impact: '1 coral colony planted',
    likes: 180,
    ownerId: 'user1',
    creatorId: 'user3',
    forSale: true,
    price: 1.8,
    category: 'Ocean Cleanup',
    isValid: true,
    isRecommended: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'nft5',
    title: 'Siberian Tiger Sanctuary',
    description: 'Supports the operations of a sanctuary for endangered Siberian tigers.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-5')?.imageUrl || '',
    impact: 'Sanctuary support',
    likes: 210,
    ownerId: 'user2',
    creatorId: 'user2',
    forSale: true,
    price: 4.5,
    category: 'Wildlife Conservation',
    isValid: false,
    isRecommended: false,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'nft6',
    title: 'Andean Cloud Forest',
    description: 'Protects 1 acre of unique cloud forest habitat in the Andes mountains.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-6')?.imageUrl || '',
    impact: '1 acre protected',
    likes: 78,
    ownerId: 'user3',
    creatorId: 'user1',
    forSale: false,
    price: 2.5,
    category: 'Reforestation',
    isValid: true,
    isRecommended: false,
    createdAt: new Date('2024-03-01'),
  },
   {
    id: 'nft7',
    title: 'Rhino Protection Unit',
    description: 'Funds an anti-poaching ranger unit for a month, protecting black rhinos.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-7')?.imageUrl || '',
    impact: '1 ranger unit funded',
    likes: 340,
    ownerId: null, // Not owned
    creatorId: 'user2',
    forSale: true,
    price: 5.0,
    category: 'Wildlife Conservation',
    isValid: true,
    isRecommended: true,
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'nft8',
    title: 'Mangrove Reforestation',
    description: 'Plants 500 mangrove saplings, crucial for coastal protection and carbon sequestration.',
    imageUrl: PlaceHolderImages.find(i => i.id === 'nft-8')?.imageUrl || '',
    impact: '500 mangroves planted',
    likes: 155,
    ownerId: 'user1',
    creatorId: 'user1',
    forSale: true,
    price: 2.0,
    category: 'Reforestation',
    isValid: true,
    isRecommended: false,
    createdAt: new Date('2024-04-01'),
  },
];

export const getUsers = (): User[] => users;
export const getUserById = (id: string): User | undefined => users.find(u => u.id === id);

export const getNfts = (): NFT[] => nfts;
export const getNftById = (id: string): NFT | undefined => nfts.find(n => n.id === id);
